version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: tora-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: Asia/Tokyo
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql

  backend:
    build: ./src/backend
    container_name: tora-backend
    command: bash -c "bundle install && rails s -b 0.0.0.0"
    volumes:
      - ./src/backend:/app         # ✅ 修正
      - bundle-volume:/usr/local/bundle
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: ${DB_USERNAME}
      DATABASE_PASSWORD: ${DB_PASSWORD}

  frontend:
    build: ./src/frontend
    container_name: tora-frontend
    command: yarn dev
    volumes:
      - ./src/frontend:/app        # ✅ 修正
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  db-data:
  bundle-volume: